apiVersion: apps/v1
kind: Deployment
metadata: 
 name: messages
 labels:
  app: messages
spec:
 selector:
  matchLabels:
   app: messages
 template:
  metadata:
   labels:
    app: messages
  spec:
   containers:
   - name: messages
     image: stuartmcg/messages:v0.3
     envFrom:
     - configMapRef:
        name: mongo-connection
---
apiVersion: v1
kind: Service
metadata:
 name: messages
spec:
 selector:
  app: messages
 ports:
 - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: messges-ingress
 annotations:
  cert-manager.io/cluster-issuer: "prod-site"
spec:
 ingressClassName: nginx
 tls:
 - hosts:
   - messages.stuartmcgillivray.com
   secretName: stuwheel-tls
 rules:
 - host: messages.stuartmcgillivray.com
   http:
    paths:
    - pathType: Prefix
      path: "/"
      backend:
       service:
        name: messages
        port:
         number: 80